import CreateCard from "@/components/CreateCard/create-card";
import Header from "@/components/Header/header";
import Head from "next/head";

export default function AppLayout({children}: any){
  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="content">
        {children}
      </div>
    </>
  )
}